### ISSUE TITLE
Search Engine Sync Issue. 

### ISSUE THREAD

**Issue by ahmed1672003** [PgOutput2Json/PgOutput2Json#3]
I use a search engine and any changes made to the database must be applied to that engine.
I want when the search engine is restarting and at the same time some changes have occurred to the database I will not be able to update the data in the search engine.
Can the package tell the database that this data is unacceptable and send it again?

**Comment by enadzan** [comment]
Please take look at the README file in the [root of the repository](https://github.com/PgOutput2Json/PgOutput2Json), particularly the [Section 3: Working with permanent replication slots](https://github.com/PgOutput2Json/PgOutput2Json?tab=readme-ov-file#3-working-with-permanent-replication-slots).

In short, permanent replication slot "remembers" what was last delivered to the client, and will deliver all changes made while the client was offline. But there are drawbacks (if the client is offline for a long time) which are described in the readme.
